# Generated by Django 4.2.5 on 2023-11-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0002_alter_rol_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='code',
            field=models.CharField(default=2, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
