from .usuario_model import Usuario
from .rol_model import Rol
from .reservas_model import Reservas
from .comentario_model import Comentarios
from .documento_model import Documento
from .inmueble_model import Inmueble
from .usuarioApartamento_model import UsuarioApartamentos
from .usuarioReserva_model import UsuariosReservas
from .vehiculo_model import Vehiculo
from .vehiculoUsuario_model import VehiculoUsuario
from .zonasComunes_model import ZonaComunes
from .pqrsd_model import PQRSD
from .registroVisitantes_model import RegistroVisitante
#from .no import Nos